<a href="https://colab.research.google.com/github/jeehu99/CPSS_Practice/blob/main/Week2_Numpy_and_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PART1 - Numpy

**1. 라이브러리 - Numpy**

In [ ]:
# 리스트로 행렬 표현

A = [[1, 0], [0, 1]]
B = [[1, 1], [1, 1]]

print(A + B)

[[1, 0], [0, 1], [1, 1], [1, 1]]


In [ ]:
# numpy를 이용한 matrix 생성

import numpy as np

A = np.array([ [1, 0], [0, 1] ])
B = np.array([ [1, 1], [1, 1] ])

print(A + B)

[[2 1]
 [1 2]]


**2. numpy vector(1차원 배열)**

In [ ]:
import numpy as np

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# vector A, B 출력
print("A == ", A, ", B == ", B)

# vector A, B shape 출력
print("A.shape == ", A.shape, ", B.shape == ", B.shape)

# vector A, B dimension 출력
print("A.ndim == ", A.ndim, ", B.ndim == ", B.ndim)

A ==  [1 2 3] , B ==  [4 5 6]
A.shape ==  (3,) , B.shape ==  (3,)
A.ndim ==  1 , B.ndim ==  1


In [ ]:
# vector 산술연산

print("A + B == ", A + B)
print("A - B == ", A - B)
print("A * B == ", A * B)
print("A / B == ", A / B)

A + B ==  [5 7 9]
A - B ==  [-3 -3 -3]
A * B ==  [ 4 10 18]
A / B ==  [0.25 0.4  0.5 ]


**3. numpy matrix(행렬)**

In [ ]:
import numpy as np

A = np.array([ [1, 2, 3], [4, 5, 6] ])
B = np.array([ [-1, -2 , -3], [-4, -5, -6] ])

print("A.shape == ", A.shape, ", B.shape == ", B.shape)
print("A.ndim == ", A.ndim, ", B.ndim == ", B.ndim)

A.shape ==  (2, 3) , B.shape ==  (2, 3)
A.ndim ==  2 , B.ndim ==  2


In [ ]:
C = np.array([1, 2, 3])
print("C.shape == ", C.shape)

# 벡터를 1 X 3 행렬로 형 변환
C = C.reshape(1, 3)
print("C.shape == ", C.shape)

C.shape ==  (3,)
C.shape ==  (1, 3)


**4. numpy 행렬 곱(dot product)**

In [ ]:
import numpy as np

A = np.array([ [1,2,3], [4,5,6] ])
B = np.array([ [-1,-2], [-3, -4], [-5, -6] ])

C = np.dot(A, B)

print("A.shape == ",A.shape, ", B.shape == ", B.shape)
print("C.shape == ", C.shape)

print(C)

A.shape ==  (2, 3) , B.shape ==  (3, 2)
C.shape ==  (2, 2)
[[-22 -28]
 [-49 -64]]


**5. numpy broadcast**

In [ ]:
import numpy as np

A = np.array([ [1, 2], [3, 4] ])
b = 5

print(A + b)

[[6 7]
 [8 9]]


In [ ]:
C = np.array([ [1, 2], [3, 4] ])
D = np.array([4, 5])

print(C + D)

[[5 7]
 [7 9]]


**6. numpy 전치행렬(transpose)**

In [ ]:
import numpy as np

A = np.array([ [1, 2], [3, 4], [5, 6] ])
B = A.T # A의 전치행렬 => 2 X 3 행렬

print(A.shape, B.shape, '\n')
print(A, '\n')
print(B)

(3, 2) (2, 3) 

[[1 2]
 [3 4]
 [5 6]] 

[[1 3 5]
 [2 4 6]]


In [ ]:
# vector 전치행렬

C = np.array([1, 2, 3, 4, 5])
D = C.T

E = C.reshape(1, 5)
F = E.T

print("C.shape == ", C.shape, ", D.shape == ", D.shape)
print("E.shape == ", E.shape, ", F.shape == ", F.shape)
print(F)

C.shape ==  (5,) , D.shape ==  (5,)
E.shape ==  (1, 5) , F.shape ==  (5, 1)
[[1]
 [2]
 [3]
 [4]
 [5]]


**7. numpy 행렬 indexing / slicing**

In [ ]:
import numpy as np

A = np.array([10, 20, 30, 40, 50, 60]).reshape(3, 2)

print(A.shape, '\n')
print(A)

(3, 2) 

[[10 20]
 [30 40]
 [50 60]]


In [ ]:
print("A[0, 0] == ", A[0, 0], ", A[0][0] == ", A[0][0])
print("A[2, 1] == ", A[2, 1], ", A[2][1] == ", A[2][1] )

A[0, 0] ==  10 , A[0][0] ==  10
A[2, 1] ==  60 , A[2][1] ==  60


In [ ]:
print("A[0:-1, 1:2] == ", A[0:-1, 1:2] )

A[0:-1, 1:2] ==  [[20]
 [40]]


In [ ]:
print("A[ :, 0] == ", A[ :, 0])
print("A[ :, :] == ", A[ :, :])

A[ :, 0] ==  [10 30 50]
A[ :, :] ==  [[10 20]
 [30 40]
 [50 60]]


**8. numpy 행렬 iterator**

In [ ]:
import numpy as np

A = np.array([ [10, 20, 30, 40], [50, 60, 70, 80] ])
print(A, '\n')
print("A.shape == ", A.shape)

it = np.nditer(A, flags=['multi_index'], op_flags=['readwrite'])

while not it.finished:
  idx = it.multi_index
  print("current value => ", A[idx])
  it.iternext()

[[10 20 30 40]
 [50 60 70 80]] 

A.shape ==  (2, 4)
current value =>  10
current value =>  20
current value =>  30
current value =>  40
current value =>  50
current value =>  60
current value =>  70
current value =>  80


**9. numpy concatenate()**

In [ ]:
import numpy as np

# 행렬에 열과 행 추가하기

A = np.array([ [10, 20, 30], [40, 50, 60] ])

print(A.shape)

# A matrix에 행(row) 추가할 행렬 => 1행 3열로 reshape
# 행을 추가하기 때문에 우선 열을 3열로 만들어야 함
row_add = np.array([70, 80, 90]).reshape(1, 3)
print(row_add.shape)

# A matrix에 열(column) 추가할 행렬 => 2행 1열로 reshape
# 열을 추가하기 때문에 우선 행을 2행으로 만들어야 함
column_add = np.array([1000, 2000]).reshape(2, 1)
print(column_add.shape)

# numpy.concatenate에서 axis = 0 행(row) 기준
# A 행렬에 row_add 행렬 추가
B = np.concatenate((A, row_add), axis=0)
print(B)

# numpy.concatenate에서 axis = 1 열(column) 기준
# A 행렬에 column_add 행렬 추가
C = np.concatenate((A, column_add), axis=1)
print(C)

(2, 3)
(1, 3)
(2, 1)
[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[  10   20   30 1000]
 [  40   50   60 2000]]


**10. numpy useful function**

In [ ]:
# colab에 파일 업로드

from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length}" bytes'.format(name=fn, length=len(uploaded[fn])))

Saving data-01-test-score.csv to data-01-test-score.csv
User uploaded file "data-01-test-score.csv" with length 326" bytes


In [ ]:
# np.loadtxt

loaded_data = np.loadtxt('./data-01-test-score.csv', delimiter=',', dtype=np.float32)

x_data = loaded_data[ :, 0:-1]
t_data = loaded_data[ :, [-1]]

print("x_data.ndim == ", x_data.ndim, ", x_data.shape == ", x_data.shape)
print("t_data.ndim == ", t_data.ndim, ", t_data.shape == ", t_data.shape)

x_data.ndim ==  2 , x_data.shape ==  (25, 3)
t_data.ndim ==  2 , t_data.shape ==  (25, 1)


In [ ]:
import numpy as np

# np.random.rand()

# 0~1 사이의 random number 발생
random_number1 = np.random.rand(3)
random_number2 = np.random.rand(1, 3)
random_number3 = np.random.rand(3, 1)

print("random_number1 == ", random_number1, ', random_number1.shape == ', random_number1.shape)
print("random_number2 == ", random_number2, ', random_number2.shape == ', random_number2.shape)
print("random_number3 == ", random_number3, ', random_number3.shape == ', random_number3.shape)

random_number1 ==  [0.78241375 0.82951854 0.7466636 ] , random_number1.shape ==  (3,)
random_number2 ==  [[0.45917479 0.3296203  0.51533613]] , random_number2.shape ==  (1, 3)
random_number3 ==  [[0.73996054]
 [0.6615543 ]
 [0.76243749]] , random_number3.shape ==  (3, 1)


In [ ]:
import numpy as np

# np.random.randint()

# 0 ~ 9 사이의 random number 발생
rand_intnum = np.random.randint(1, 10, (3, 3))

print(rand_intnum)

[[1 5 9]
 [9 8 6]
 [2 4 9]]


In [ ]:
import numpy as np

# np.sum(), np.exp(), np.log()

X = np.array([2, 4, 6, 8])
print("np.sum(X) == ", np.sum(X))
print("np.exp(X) == ", np.exp(X))
print("np.log(X) == ", np.log(X))

np.sum(X) ==  20
np.exp(X) ==  [   7.3890561    54.59815003  403.42879349 2980.95798704]
np.log(X) ==  [0.69314718 1.38629436 1.79175947 2.07944154]


In [ ]:
import numpy as np

# numpy.max(), numpy.min(), numpy.argmax(), numpy.argmin()

X = np.array([2, 4, 6, 8])

print('np.max(X) == ', np.max(X))
print('np.min(X) == ', np.min(X))
print('np.argmax(X) == ', np.argmax(X))
print('np.argmin(X) == ', np.argmin(X))

np.max(X) ==  8
np.min(X) ==  2
np.argmax(X) ==  3
np.argmin(X) ==  0


In [ ]:
import numpy as np

X = np.array([ [2, 4, 6], [1, 2, 3], [0, 5, 8] ])
print(X)

print('np.max(X) == ', np.max(X, axis=0))
print('np.min(X) == ', np.min(X, axis=0))

print('np.max(X) == ', np.max(X, axis=1))
print('np.min(X) == ', np.min(X, axis=1))

print('np.argmax(X) == ', np.argmax(X, axis=0))
print('np.argmin(X) == ', np.argmin(X, axis=0))

print('np.argmax(X) == ', np.argmax(X, axis=1))
print('np.argmin(X) == ', np.argmin(X, axis=1))

[[2 4 6]
 [1 2 3]
 [0 5 8]]
np.max(X) ==  [2 5 8]
np.min(X) ==  [0 2 3]
np.max(X) ==  [6 3 8]
np.min(X) ==  [2 1 0]
np.argmax(X) ==  [0 2 2]
np.argmin(X) ==  [2 1 1]
np.argmax(X) ==  [2 2 2]
np.argmin(X) ==  [0 0 0]


In [ ]:
import numpy as np

# numpy.ones(), numpy.zeros()

A = np.ones([3, 3])
print("A.shape == ", A.shape, "\nA == ", A, '\n')

B = np.zeros([3, 2])
print("B.shape == ", B.shape, '\nB == ', B)

A.shape ==  (3, 3) 
A ==  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

B.shape ==  (3, 2) 
B ==  [[0. 0.]
 [0. 0.]
 [0. 0.]]


# PART2 - Pandas

**1. 시리즈(Series)**

In [ ]:
import pandas as pd

array = pd.Series(['사과', '포도', '딸기'], index=['a', 'b', 'c'])

print(array)
print(array['a'])

a    사과
b    포도
c    딸기
dtype: object
사과


In [ ]:
import pandas as pd

# Dict 자료형을 Series로 변환

fruit_dict = {
    'a' : '사과',
    'b' : '포도',
    'c' : '딸기'
}

fruit_array = pd.Series(fruit_dict)
print(fruit_array['a'])

사과


**2. 데이터 프레임**

In [ ]:
import pandas as pd

fruit_dict = {
    'Apple' : '사과',
    'Grape' : '포도',
    'Strawberry' : '딸기'
}

count_dict = {
    'Apple' : 3,
    'Grape' : 5,
    'Strawberry' : 7 
}

fruit_name = pd.Series(fruit_dict)
cnt = pd.Series(count_dict)

# 이름(Name) : 값(Values)
df_fruit = pd.DataFrame({
    'name' : fruit_name,
    'count' : cnt
})

print(df_fruit)

           name  count
Apple        사과      3
Grape        포도      5
Strawberry   딸기      7


**3. 시리즈의 연산**

In [ ]:
import pandas as pd

fruit_dict = {
    'Apple' : '사과',
    'Grape' : '포도',
    'Strawberry' : '딸기'
}

count_dict = {
    'Apple' : 3,
    'Grape' : 5,
    'Strawberry' : 7
}

pref_dict = {
    'Apple' : 1,
    'Grape' : 2,
    'Strawberry' : 3
}

fruit_name = pd.Series(fruit_dict)
cnt = pd.Series(count_dict)
pref = pd.Series(pref_dict)

df_fruit = pd.DataFrame({
    'fruit' : fruit_name,
    'count' : cnt,
    'preference' : pref
})

score = df_fruit['count'] * df_fruit['preference']
df_fruit['score'] = score

print(df_fruit)

           fruit  count  preference  score
Apple         사과      3           1      3
Grape         포도      5           2     10
Strawberry    딸기      7           3     21


**4. 데이터 프레임의 슬라이싱**

In [ ]:
import pandas as pd

fruit_dict = {
    'Apple' : '사과',
    'Grape' : '포도',
    'Strawberry' : '딸기',
    'Orange' : '오렌지'
}

count_dict = {
    'Apple' : 3,
    'Grape' : 5,
    'Strawberry' : 7,
    'Orange' : 4
}

pref_dict = {
    'Apple' : 1,
    'Grape' : 2,
    'Strawberry' : 3,
    'Orange' : 1
}

fruit_name = pd.Series(fruit_dict)
cnt = pd.Series(count_dict)
pref = pd.Series(pref_dict)

df_fruit = pd.DataFrame({
    'fruit' : fruit_name,
    'count' : cnt,
    'preference' : pref
})

print(df_fruit)


# 이름을 기준으로 슬라이싱
# Grape ~ Strawberry 까지 데이터를 가져오고, count부터 모든 series를 가져옴
print(df_fruit.loc['Grape':'Strawberry', 'count':])

# 인덱스를 기준으로 슬라이싱
# 1 ~ (3-1) 번째 인덱스를 가져오고, series 인덱스 1부터 가져옴
print(df_fruit.iloc[1:3, 1:])

           fruit  count  preference
Apple         사과      3           1
Grape         포도      5           2
Strawberry    딸기      7           3
Orange       오렌지      4           1
            count  preference
Grape           5           2
Strawberry      7           3
            count  preference
Grape           5           2
Strawberry      7           3


**5. 데이터 프레임의 연산**

In [ ]:
import pandas as pd

fruit_dict = {
    'Apple' : '사과',
    'Grape' : '포도',
    'Strawberry' : '딸기',
    'Orange' : '오렌지'
}

count_dict = {
    'Apple' : 3,
    'Grape' : 5,
    'Strawberry' : 7,
    'Orange' : 4
}

pref_dict = {
    'Apple' : 1,
    'Grape' : 2,
    'Strawberry' : 3,
    'Orange' : 1
}

fruit_name = pd.Series(fruit_dict)
cnt = pd.Series(count_dict)
pref = pd.Series(pref_dict)

df_fruit = pd.DataFrame({
    'fruit' : fruit_name,
    'count' : cnt,
    'preference' : pref
})

print(df_fruit)

df_fruit.loc['Apple', 'preference'] = 3      # 데이터의 변경
df_fruit.loc['Banana'] = ['바나나', 5, 3]    # 새 데이터 삽입

print(df_fruit)

           fruit  count  preference
Apple         사과      3           1
Grape         포도      5           2
Strawberry    딸기      7           3
Orange       오렌지      4           1
           fruit  count  preference
Apple         사과      3           3
Grape         포도      5           2
Strawberry    딸기      7           3
Orange       오렌지      4           1
Banana       바나나      5           3


**6. 엑셀로 내보내기 / 불러오기**

In [ ]:
import pandas as pd

fruit_dict = {
    'Apple' : '사과',
    'Grape' : '포도',
    'Strawberry' : '딸기',
    'Orange' : '오렌지'
}

count_dict = {
    'Apple' : 3,
    'Grape' : 5,
    'Strawberry' : 7,
    'Orange' : 4
}

pref_dict = {
    'Apple' : 1,
    'Grape' : 2,
    'Strawberry' : 3,
    'Orange' : 1
}

fruit_name = pd.Series(fruit_dict)
cnt = pd.Series(count_dict)
pref = pd.Series(pref_dict)

df_fruit = pd.DataFrame({
    'fruit' : fruit_name,
    'count' : cnt,
    'preference' : pref
})

# to_csv 함수를 이용하여 내보내기(한글 데이터를 잘처리하기 위해서 utf-8-sig)
df_fruit.to_csv("fruit.csv", encoding='utf-8-sig')
#데이터를 불러오기 위해서 pandas에 있는 read_csv 함수 사용
saved = pd.read_csv("fruit.csv", index_col=0)
print(saved)

!ls -al

           fruit  count  preference
Apple         사과      3           1
Grape         포도      5           2
Strawberry    딸기      7           3
Orange       오렌지      4           1
total 20
drwxr-xr-x 1 root root 4096 Mar  9 04:56 .
drwxr-xr-x 1 root root 4096 Mar  9 04:54 ..
drwxr-xr-x 4 root root 4096 Mar  7 14:44 .config
-rw-r--r-- 1 root root  104 Mar  9 04:56 fruit.csv
drwxr-xr-x 1 root root 4096 Mar  7 14:45 sample_data


**7. 데이터 프레임의 Null 여부 확인**

In [ ]:
import numpy as np
import pandas as pd

fruit_dict = {
    'Apple' : '사과',
    'Grape' : '포도',
    'Strawberry' : '딸기',
    'Orange' : '오렌지'
}

count_dict = {
    'Apple' : 3,
    'Grape' : 5,
    'Strawberry' : np.nan,
    'Orange' : 4
}

pref_dict = {
    'Apple' : 1,
    'Grape' : 2,
    'Strawberry' : 3,
    'Orange' : 1
}

fruit_name = pd.Series(fruit_dict)
cnt = pd.Series(count_dict)
pref = pd.Series(pref_dict)

df_fruit = pd.DataFrame({
    'fruit' : fruit_name,
    'count' : cnt,
    'preference' : pref
})

print(df_fruit, '\n')
print(df_fruit.notnull(), '\n')
print(df_fruit.isnull(), '\n')
df_fruit['count'] = df_fruit['count'].fillna('데이터 없음')
print(df_fruit)

           fruit  count  preference
Apple         사과    3.0           1
Grape         포도    5.0           2
Strawberry    딸기    NaN           3
Orange       오렌지    4.0           1 

            fruit  count  preference
Apple        True   True        True
Grape        True   True        True
Strawberry   True  False        True
Orange       True   True        True 

            fruit  count  preference
Apple       False  False       False
Grape       False  False       False
Strawberry  False   True       False
Orange      False  False       False 

           fruit   count  preference
Apple         사과     3.0           1
Grape         포도     5.0           2
Strawberry    딸기  데이터 없음           3
Orange       오렌지     4.0           1


**8. 시리즈 자료형의 연산**

In [ ]:
import pandas as pd

array1 = pd.Series([1, 2, 3], index=['A', 'B', 'C'])
array2 = pd.Series([4, 5, 6], index=['B', 'C', 'D'])

add1_array = array1.add(array2)
print(add1_array, '\n')

add2_array = array1.add(array2, fill_value=0)
print(add2_array)

A    NaN
B    6.0
C    8.0
D    NaN
dtype: float64 

A    1.0
B    6.0
C    8.0
D    6.0
dtype: float64


**9. 데이터 프레임 자료형의 연산**

In [ ]:
import pandas as pd

df1 = pd.DataFrame([ [1, 2], [3, 4] ], index=['A', 'B'])
df2 = pd.DataFrame([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ], index=['B', 'C', 'D'])

print(df1, '\n')
print(df2, '\n')

add_df = df1.add(df2, fill_value=0)
print(add_df)

   0  1
A  1  2
B  3  4 

   0  1  2
B  1  2  3
C  4  5  6
D  7  8  9 

     0    1    2
A  1.0  2.0  NaN
B  4.0  6.0  3.0
C  4.0  5.0  6.0
D  7.0  8.0  9.0


**10. 데이터 프레임 집계 함수**

In [ ]:
import pandas as pd

df1 = pd.DataFrame([ [1, 2], [3, 4] ], index=['A', 'B'])
df2 = pd.DataFrame([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ], index=['B', 'C', 'D'])

add_df = df1.add(df2, fill_value=0)
print(add_df, '\n')
print('컬럼 1의 합: ', add_df[1].sum(), '\n')
print('모든 컬럼 각각의 합: \n', add_df.sum())

     0    1    2
A  1.0  2.0  NaN
B  4.0  6.0  3.0
C  4.0  5.0  6.0
D  7.0  8.0  9.0 

컬럼 1의 합:  21.0 

모든 컬럼 각각의 합: 
 0    16.0
1    21.0
2    18.0
dtype: float64


**11. 데이터 프레임 정렬 함수**

In [ ]:
import pandas as pd
import numpy as np

fruit_dict = {
    'Apple' : '사과',
    'Grape' : '포도',
    'Strawberry' : '딸기',
    'Orange' : '오렌지'
}

count_dict = {
    'Apple' : 3,
    'Grape' : 5,
    'Strawberry' : 7,
    'Orange' : 4
}

pref_dict = {
    'Apple' : 1,
    'Grape' : 2,
    'Strawberry' : 3,
    'Orange' : 1
}

fruit_name = pd.Series(fruit_dict)
cnt = pd.Series(count_dict)
pref = pd.Series(pref_dict)

df_fruit = pd.DataFrame({
    'fruit' : fruit_name,
    'count' : cnt,
    'preference' : pref
})

print(df_fruit, '\n')
df_fruit = df_fruit.sort_values('count', ascending=False)
print(df_fruit)

           fruit  count  preference
Apple         사과      3           1
Grape         포도      5           2
Strawberry    딸기      7           3
Orange       오렌지      4           1 

           fruit  count  preference
Strawberry    딸기      7           3
Grape         포도      5           2
Orange       오렌지      4           1
Apple         사과      3           1


**12. 데이터 프레임의 마스킹**

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randint(1, 10, (2, 2)), index=[0, 1], columns=["A", "B"])
print(df, '\n')

print('컬럼 A의 각 원소가 5보다 작거나 같은지 출력')
print(df['A'] <= 5, '\n')

print('컬럼 A의 원소가 5보다 작거나 같고, 컬럼 B의 원소가 8보다 작거나 같은 행 추출')
print(df.query("A <= 5 and B <= 8"))

   A  B
0  5  9
1  1  4 

컬럼 A의 각 원소가 5보다 작거나 같은지 출력
0    True
1    True
Name: A, dtype: bool 

컬럼 A의 원소가 5보다 작거나 같고, 컬럼 B의 원소가 8보다 작거나 같은 행 추출
   A  B
1  1  4


**13. 데이터 프레임의 개별 연산**

In [ ]:
import pandas as pd

# apply 함수를 이용

df = pd.DataFrame([ [1, 2, 3, 4], [1, 2, 3, 4] ], index=[0, 1], columns=['A', 'B', 'C', 'D'])
print(df, '\n')

df = df.apply(lambda x: x + 1)
print(df, '\n')

def add_one(x):
  return x + 1

df = df.apply(add_one)
print(df)

   A  B  C  D
0  1  2  3  4
1  1  2  3  4 

   A  B  C  D
0  2  3  4  5
1  2  3  4  5 

   A  B  C  D
0  3  4  5  6
1  3  4  5  6


In [ ]:
import pandas as pd

# replace를 사용하여 특정한 데이터를 찾아서 그 데이터만을 변경

df = pd.DataFrame([ ['Apple', 'Grape', 'Strawberry', 'Orange'],
                   ['Banana', 'Carrot', 'Potato', 'Cucumber'] ],
                  index=[0, 1], columns=['A', 'B', 'C', 'D'])

print(df,'\n')
df = df.replace({'Apple':'Peach'})
print(df)

        A       B           C         D
0   Apple   Grape  Strawberry    Orange
1  Banana  Carrot      Potato  Cucumber 

        A       B           C         D
0   Peach   Grape  Strawberry    Orange
1  Banana  Carrot      Potato  Cucumber


**14. 데이터 프레임의 그룹화**

In [ ]:
import pandas as pd

# groupby 함수

df = pd.DataFrame([ ['Apple', 7, 'Fruit'],
                   ['Grape', 3, 'Fruit'],
                   ['Carrot', 5, 'Vegetable'],
                   ['Potato', 4, 'Vegetable'] ],
                  columns=['Name', 'Count', 'Type'])
print(df, '\n')
print(df.groupby(['Type']).sum())

     Name  Count       Type
0   Apple      7      Fruit
1   Grape      3      Fruit
2  Carrot      5  Vegetable
3  Potato      4  Vegetable 

           Count
Type            
Fruit         10
Vegetable      9


In [ ]:
# aggregate 함수: 여러 개의 groupby 연산을 수행할 수 있음

import numpy as np
import pandas as pd

df = pd.DataFrame([ ['Apple', 7, 1, 'Fruit'],
                   ['Grape', 3, 4, 'Fruit'],
                   ['Carrot', 5, 3, 'Vegetable'],
                   ['Potato', 4, 2, 'Vegetable'] ],
                  columns=['Name', 'Count', 'Preference', 'Type'])
print(df, '\n')
print(df.groupby(['Type']).aggregate([min, max, np.average]))

     Name  Count  Preference       Type
0   Apple      7           1      Fruit
1   Grape      3           4      Fruit
2  Carrot      5           3  Vegetable
3  Potato      4           2  Vegetable 

          Count             Preference            
            min max average        min max average
Type                                              
Fruit         3   7     5.0          1   4     2.5
Vegetable     4   5     4.5          2   3     2.5


/usr/local/lib/python3.7/dist-packages/pandas/core/groupby/generic.py:303: FutureWarning: Dropping invalid columns in SeriesGroupBy.agg is deprecated. In a future version, a TypeError will be raised. Before calling .agg, select only columns which should be valid for the aggregating function.
  results[key] = self.aggregate(func)


In [ ]:
import pandas as pd

# groupby로 나온 결과에 대해서 필터링을 수행한 결과 구하기

df = pd.DataFrame([ ['Apple', 7, 1, 'Fruit'],
                   ['Grape', 3, 4, 'Fruit'],
                   ['Carrot', 5, 3, 'Vegetable'],
                   ['Potato', 4, 2, 'Vegetable'] ],
                  columns=['Name', 'Count', 'Preference', 'Type'])

def my_filter(data):
  return data['Count'].mean() >= 5

print(df,'\n')

# Type 별로 묶기
df = df.groupby("Type").filter(my_filter)
# Count의 평균 값이 5 이상인 Type의 값만 출력
print(df)

     Name  Count  Preference       Type
0   Apple      7           1      Fruit
1   Grape      3           4      Fruit
2  Carrot      5           3  Vegetable
3  Potato      4           2  Vegetable 

    Name  Count  Preference   Type
0  Apple      7           1  Fruit
1  Grape      3           4  Fruit


In [ ]:
import pandas as pd

# Vegetable이라는 Type의 데이터만 가져오기

df = pd.DataFrame([ ['Apple', 7, 1, 'Fruit'],
                   ['Grape', 3, 4, 'Fruit'],
                   ['Carrot', 5, 3, 'Vegetable'],
                   ['Potato', 4, 2, 'Vegetable'] ],
                  columns=['Name', 'Count', 'Preference', 'Type'])
df = df.groupby("Type").get_group("Vegetable")
print(df)

     Name  Count  Preference       Type
2  Carrot      5           3  Vegetable
3  Potato      4           2  Vegetable


In [ ]:
import pandas as pd

# Type에 따라 그룹을 지은 후 Count의 mean 값과 얼마나 차이가 나는지 계산해서 Gap에 삽입

df = pd.DataFrame([ ['Apple', 7, 1, 'Fruit'],
                   ['Grape', 3, 4, 'Fruit'],
                   ['Carrot', 5, 3, 'Vegetable'],
                   ['Potato', 4, 2, 'Vegetable'] ],
                  columns=['Name', 'Count', 'Preference', 'Type'])

df['Gap'] = df.groupby("Type")["Count"].apply(lambda x : x - x.mean())
print(df)

     Name  Count  Preference       Type  Gap
0   Apple      7           1      Fruit  2.0
1   Grape      3           4      Fruit -2.0
2  Carrot      5           3  Vegetable  0.5
3  Potato      4           2  Vegetable -0.5


**15. 데이터 프레임의 다중화**

In [ ]:
import pandas as pd
import numpy as np

# 인덱스를 다중화해서 설정할 수 있음

df = pd.DataFrame(
    np.random.randint(1, 10, (4, 4)),
    index = [['1차', '1차', '2차', '2차'], ['공격', '수비', '공격', '수비']],
    columns = ['1회', '2회', '3회', '4회']
)

print(df, '\n')
# 2차 공격/수비의 1회, 2회 데이터를 출력
print(df[['1회', '2회']].loc['2차'])

       1회  2회  3회  4회
1차 공격   3   8   9   8
   수비   9   8   3   6
2차 공격   5   9   4   7
   수비   5   4   3   9 

    1회  2회
공격   5   9
수비   5   4
